{{- if or (.Values.satisfy.sshPrivateKey) (.Values.satisfy.oauthToken) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "satisfy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "satisfy.name" . }}
    helm.sh/chart: {{ include "satisfy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
{{- if .Values.satisfy.sshPrivateKey }}
  SSH_PRIVATE_KEY: {{ .Values.satisfy.sshPrivateKey | b64enc }}
{{- end }}
{{- if .Values.satisfy.oauthToken }}
  GITHUB_OAUTH: {{ .Values.satisfy.oauthToken | b64enc }}
{{- end }}  
{{- end -}}

