on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  container_image_name: satisfy

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Update SHA
        run: echo $GITHUB_SHA > $GITHUB_WORKSPACE/_meta

      - name: Build container image
        run: docker build -t alphaceti/${container_image_name}:$(echo $GITHUB_SHA | head -c7) ./docker
